# Generated by Django 2.2.5 on 2019-10-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitings',
            name='patient',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
