# Generated by Django 2.2.5 on 2019-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='family_doctor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
