# Generated by Django 2.2.5 on 2019-10-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20191020_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('docotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Patient')),
            ],
            options={
                'verbose_name': 'Направлення',
                'verbose_name_plural': 'Направлення',
            },
        ),
    ]
