# Generated by Django 2.2.5 on 2019-10-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20191029_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='text_type',
        ),
        migrations.AlterField(
            model_name='card',
            name='conclusion',
            field=models.CharField(max_length=100, null=True, verbose_name='Заключення'),
        ),
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(verbose_name='Текст запису'),
        ),
    ]
