# Generated by Django 2.2.5 on 2019-10-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20191029_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='c_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
