# Generated by Django 2.2.5 on 2019-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_card_c_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
