# Generated by Django 2.2.5 on 2019-10-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_doctor_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
