# Generated by Django 2.2.5 on 2019-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_auto_20191031_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=16)),
                ('casta', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='type1',
        ),
        migrations.AddField(
            model_name='word',
            name='code',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
