# Generated by Django 2.2.5 on 2019-11-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20191031_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('date_birth', models.DateTimeField(null=True)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Реєстратор',
                'verbose_name_plural': 'Реєстратори',
            },
        ),
    ]
