# Generated by Django 2.2.5 on 2019-11-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_registry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='key',
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
