# Generated by Django 2.2.5 on 2019-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_analysistemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistemplate',
            name='template',
            field=models.TextField(),
        ),
    ]
