# Generated by Django 2.2.5 on 2019-11-03 12:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_auto_20191102_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistemplate',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
