# Generated by Django 2.2.5 on 2019-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_auto_20191103_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistemplate',
            name='template',
            field=models.TextField(),
        ),
    ]
