# Generated by Django 2.2.5 on 2019-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_auto_20191103_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabolatoryVisitings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoryAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='c_type',
        ),
        migrations.AddField(
            model_name='card',
            name='content_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='second_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
