# Generated by Django 2.2.5 on 2019-11-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_auto_20191103_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='labolatoryvisitings',
            name='analys_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.AnalysisTemplate'),
        ),
        migrations.AddField(
            model_name='labolatoryvisitings',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='labolatoryvisitings',
            name='is_prow',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='labolatoryvisitings',
            name='laborant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.LaboratoryAssistant'),
        ),
        migrations.AddField(
            model_name='labolatoryvisitings',
            name='patient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Patient'),
        ),
    ]
