# Generated by Django 2.2.5 on 2019-11-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_auto_20191104_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='visiting_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.VisitingsTemplate'),
        ),
    ]
