# Generated by Django 2.2.5 on 2019-11-08 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_auto_20191108_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitings',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Patient'),
        ),
    ]
