# Generated by Django 2.2.5 on 2019-11-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_auto_20191108_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='ecp',
        ),
        migrations.AddField(
            model_name='card',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Doctor'),
        ),
    ]
