# Generated by Django 2.2.5 on 2019-11-11 20:52

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_auto_20191111_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='conclusion',
            field=fernet_fields.fields.EncryptedTextField(max_length=100, null=True, verbose_name='Заключення'),
        ),
        migrations.AlterField(
            model_name='card',
            name='content',
            field=fernet_fields.fields.EncryptedTextField(verbose_name='Текст запису'),
        ),
    ]
