# Generated by Django 2.2.5 on 2019-11-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0032_familydoctorvotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyDoctorVotes',
        ),
    ]
