# Generated by Django 2.2.5 on 2019-11-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0034_familydoctorvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='can_vote',
            field=models.BooleanField(default=False),
        ),
    ]
