# Generated by Django 2.2.5 on 2019-11-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0035_patient_can_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='can_vote',
            field=models.FloatField(default=False),
        ),
    ]
