# Generated by Django 2.2.5 on 2019-10-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('family_doctor', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Пацієнт',
                'verbose_name_plural': 'Пацієнти',
            },
        ),
        migrations.CreateModel(
            name='Visitings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('is_in', models.BooleanField(default=False)),
                ('if_go', models.BooleanField(default=True)),
                ('docotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Doctor')),
            ],
            options={
                'verbose_name': 'Прийом',
                'verbose_name_plural': 'Прийоми',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text_type', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('conclusion', models.CharField(max_length=100)),
                ('ecp', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Patient')),
            ],
            options={
                'verbose_name': 'Картка',
                'verbose_name_plural': 'Картка',
            },
        ),
    ]
