# Generated by Django 2.2.5 on 2019-10-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_directions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitings',
            old_name='time',
            new_name='date',
        ),
    ]
