# Generated by Django 2.2.5 on 2019-11-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_auto_20191103_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labolatoryvisitings',
            name='analys_type',
            field=models.TextField(default=None, null=True),
        ),
    ]
