# Generated by Django 2.2.5 on 2019-11-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_auto_20191109_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directions',
        ),
    ]
