# Generated by Django 2.2.5 on 2019-11-11 13:38

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_delete_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='previous_hash',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='key',
            field=fernet_fields.fields.EncryptedCharField(max_length=33),
        ),
    ]
